excluded:
  - ${PWD}/**/.build
  - ${PWD}/.git

switch_case_alignment:
  indented_cases: true

line_length:
  warning: 140
  ignores_interpolated_strings: true

nesting:
  type_level: 3

file_length:
  ignore_comment_only_lines: true

force_unwrapping:
  severity: error

opt_in_rules:
  - force_unwrapping

disabled_rules:
  - identifier_name
  - opening_brace
  - statement_position
  - syntactic_sugar
  - todo
  - trailing_comma
  - type_body_length
  - type_name
