// Copyright (c) 2026 The swift-multiarray authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

public struct BoxPropertyMacro: AccessorMacro, PeerMacro {
    // AccessorMacro: adds a get accessor (and set for var) that transparently
    // wraps and unwraps the Box backing store.
    public static func expansion(
        of _: AttributeSyntax,
        providingAccessorsOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [AccessorDeclSyntax] {
        guard let varDecl = declaration.as(VariableDeclSyntax.self), varDecl.bindings.count == 1,
              let binding = varDecl.bindings.first,
              let identifier = binding.pattern.as(IdentifierPatternSyntax.self) else
        {
            let message = MacroExpansionErrorMessage("@Box can only be applied to a stored property")
            if let namedDecl = declaration.asProtocol(NamedDeclSyntax.self) {
                context.diagnose(Diagnostic(node: namedDecl.name, message: message))
            }
            else {
                context.diagnose(Diagnostic(node: declaration, message: message))
            }
            return []
        }
        guard binding.typeAnnotation != nil else {
            let name = identifier.identifier.text
            let message = MacroExpansionErrorMessage(
                "@Box requires an explicit type annotation on stored property '\(name)'"
            )
            context.diagnose(Diagnostic(node: identifier, message: message))
            return []
        }
        let back = "_\(identifier.identifier.text)"
        let inline = varDecl.modifiers.contains {
            $0.name.tokenKind == .keyword(.private) || $0.name.tokenKind == .keyword(.fileprivate)
        } ? "" : "@inlinable "
        return [
            "\(raw: inline)get { \(raw: back).unbox }",
            "\(raw: inline)set { \(raw: back) = Box(newValue) }",
        ]
    }

    // PeerMacro: emits the backing stored property `_name: Box<Type>`.
    // Marked @usableFromInline so the @inlinable init(from:) generated by @Generic
    // can assign to it when the enclosing struct is public.
    public static func expansion(
        of _: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in _: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let varDecl = declaration.as(VariableDeclSyntax.self), varDecl.bindings.count == 1,
              let binding = varDecl.bindings.first,
              let identifier = binding.pattern.as(IdentifierPatternSyntax.self),
              let type = binding.typeAnnotation?.type else
        {
            return []
        }

        let name = identifier.identifier.text
        let typeStr = type.trimmed.description
        let isPublic = varDecl.modifiers.contains {
            $0.name.tokenKind == .keyword(.public) || $0.name.tokenKind == .keyword(.package)
        }
        let initializer = binding.initializer.map { " = Box(\($0.value.trimmed.description))" } ?? ""
        let attr: DeclSyntax = isPublic
            ? "@usableFromInline var _\(raw: name): Box<\(raw: typeStr)>\(raw: initializer)"
            : "var _\(raw: name): Box<\(raw: typeStr)>\(raw: initializer)"
        return [attr]
    }
}
