name: Pull Request

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat
        run: scripts/format.sh --lint --reporter github-actions-log

  test-ubuntu-latest:
    name: Test Swift 6.2 Ubuntu Latest
    runs-on: ubuntu-latest
    container: swift:6.2
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: scripts/test-linux.sh -Xswiftc -warnings-as-errors

  test-macos-26:
    name: Test Swift 6.2 macos-26
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: scripts/test-macos.sh -Xswiftc -warnings-as-errors
